manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 5d9920406c662608aecdb486e5a299fdea93a478
      import: app/west.yml
  self:
    path: config
