manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 9f1c2e7c1a0b3d4e5f6a7b8c9d0e1f2a3b4c5d6
      import: app/west.yml
  self:
    path: config
